### ISSUE TITLE
Single quotes within data fields are eliminated

### ISSUE THREAD

**Issue by jkrenge** [parcelLab/edi-iftmin#1]
When parsing an EDIFACT file with single quotes in data fields, they are eliminated and replaced with an emptry string when giving the parsed JSON object.

---
### Example

The single quote in the city name in field `NAD.CN.060` gets lost.

```
NAD: Name and address
   CN: Consignee (raw: NAD+CN+++MAX MUSTERMANN+SAMPLE STREET 123+CHANDLER'S FORD,EASTLEIGH++SO54 2IS+GB)
     010: Party Function Code Qualifier # CN
     020: Party identification details
     030: Name and address
     040: Party name # MAX MUSTERMANN
     050: Street # SAMPLE STREET 123
     060: City name # CHANDLER'S FORD,EASTLEIGH
     070: Country sub-entity details
     080: Postal identification code # SO54 2IS
     090: Country name code # GB
```

---
### Cause

The function `splitIntoDataElements(message)` in [index.js#L63](https://github.com/parcelLab/edi-iftmin/blob/master/index.js#L63) removes all single quotes. This needs to be checked if this is necessary or can be omitted.

```
function splitIntoDataElements(message) {
  // FIXME: Check if this removing of single quotes is necessary
  return message.replace(/\'/g, '').split('+');
}
```

**Comment by sehecker** [comment]
4 years old, I think we can close this one, right?

**Comment by jkrenge** [comment]
Okay
